### ISSUE TITLE
Deleted records are not being fetched by default

### ISSUE THREAD

**Issue by BernardoMG** [revelrylabs/ecto_soft_delete#140] opened 2022-03-10 17:34 UTC
Hi 👋

If I understood correctly, deleted records should be fetched by default e.g.

```elixir
Record |> Repo.all()
```

However, I see a `deleted_at IS NULL` clause being applied. Is this correct or is it a known issue? 

Your documentation suggests this would only happen if I use the `with_undeleted` query.

I need to do something like this to fetch all records

```elixir
Record
|> where([record], not is_nil(record.deleted_at))
|> or_where([record], is_nil(record.deleted_at))
|> Repo.all()
```

Thank you!

**Comment by zdcthomas** [comment] 2022-04-19 20:09
This looks like the intended behavior of the lib, after looking at https://github.com/revelrylabs/ecto_soft_delete/blob/327d3c9e0a8efa2b67efb46ff34578419aa8b051/lib/ecto/soft_delete_repo.ex#L79

**Comment by Dacello** [comment] 2022-07-05 19:15
@BernardoMG Hi there, yea sorry -- our documentation is out of date on this front. @zdcthomas You are correct -- soft deleted records are excluded implicitly. You can include them by adding `with_deleted: true` to the `Repo` operation, e.g. 
```
Repo.all(Record, with_deleted: true)
```

**Comment by Dacello** [comment] 2022-07-05 19:17
Gonna close this since its intended behavior

**Closed as completed by Dacello** 2022-07-05 19:17 UTC
